import {
  Archive,
  BadgePercent,
  Bell,
  BellRing,
  Bold,
  BookMarked,
  BookOpenText,
  CalendarDays,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CirclePlay,
  CircleCheck,
  CircleX,
  Cloud,
  CloudUpload,
  CloudSun,
  Code2,
  Download,
  EllipsisVertical,
  Eye,
  FileText,
  Film,
  Folder,
  FolderOpen,
  FolderTree,
  Globe,
  Image,
  Italic,
  Languages,
  LayoutDashboard,
  LayoutGrid,
  List,
  ListFilter,
  ListOrdered,
  LogOut,
  Mail,
  Megaphone,
  Menu,
  MessageCircle,
  Minus,
  Newspaper,
  PencilLine,
  Plus,
  UserPlus,
  Rss,
  Search,
  Settings,
  Share2,
  Underline,
  ThumbsUp,
  Trash2,
  TrendingUp,
  TrendingDown,
  Upload,
  Smartphone,
  Laptop,
  Tablet,
  AlignCenter,
  AlignLeft,
  Clock3,
  Link2,
  Quote,
  UserCog,
  UserRound,
  Users,
  X,
  Star,
  Ellipsis,
  MessageSquare,
  ShieldAlert,
  Ban,
  CircleHelp,
  Gavel,
} from 'lucide-react'

const iconMap = {
  calendar_today: CalendarDays,
  partly_cloudy_day: CloudSun,
  menu: Menu,
  person: UserRound,
  play_circle: CirclePlay,
  trending_up: TrendingUp,
  search: Search,
  social_leaderboard: Megaphone,
  share: Share2,
  rss_feed: Rss,
  notifications: Bell,
  notifications_active: BellRing,
  account_circle: UserRound,
  forum: MessageSquare,
  chat_bubble: MessageCircle,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  public: Globe,
  auto_stories: BookOpenText,
  cloud: Cloud,
  bookmark: BookMarked,
  thumb_up: ThumbsUp,
  mail: Mail,
  language: Languages,
  newspaper: Newspaper,
  dashboard: LayoutDashboard,
  article: FileText,
  category: FolderTree,
  person_edit: UserCog,
  campaign: Megaphone,
  group: Users,
  settings: Settings,
  visibility: Eye,
  loyalty: BadgePercent,
  edit_note: PencilLine,
  remove: Minus,
  filter_list: ListFilter,
  download: Download,
  file_download: Download,
  more_vert: EllipsisVertical,
  add: Plus,
  person_add: UserPlus,
  logout: LogOut,
  grid_view: LayoutGrid,
  image: Image,
  movie: Film,
  folder: Folder,
  archive: Archive,
  folder_open: FolderOpen,
  upload_file: Upload,
  view_module: LayoutGrid,
  list: List,
  calendar_month: CalendarDays,
  expand_more: ChevronDown,
  close: X,
  help_outline: CircleHelp,
  description: FileText,
  delete: Trash2,
  format_bold: Bold,
  format_italic: Italic,
  format_underlined: Underline,
  link: Link2,
  format_quote: Quote,
  code: Code2,
  format_list_bulleted: List,
  format_list_numbered: ListOrdered,
  format_align_left: AlignLeft,
  format_align_center: AlignCenter,
  cloud_upload: CloudUpload,
  schedule: Clock3,
  pending_actions: Clock3,
  timer: Clock3,
  groups: Users,
  exit_to_app: LogOut,
  smartphone: Smartphone,
  laptop: Laptop,
  tablet: Tablet,
  arrow_upward: TrendingUp,
  arrow_downward: TrendingDown,
  report: ShieldAlert,
  block: Ban,
  check_circle: CircleCheck,
  cancel: CircleX,
  gavel: Gavel,
  stars: Star,
  more_horiz: Ellipsis,
}

function Icon({ name, className = '' }) {
  const IconComponent = iconMap[name]

  if (!IconComponent) {
    return null
  }

  return <IconComponent aria-hidden="true" className={`h-4 w-4 shrink-0 ${className}`.trim()} strokeWidth={2} />
}

export default Icon

